# Generated by Django 6.0.7 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('on_hand', models.DecimalField(decimal_places=2, help_text='Current stock in kg', max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, help_text='Buy when stock falls to or below this', max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=2, help_text='How much to buy when triggered', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
