# Generated by Django 6.0.7 on 2026-08-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
