# Generated by Django 6.0.8 on 2026-08-26 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPCUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(blank=True, max_length=300)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(help_text='master / demand / plan / erp / forecast', max_length=20)),
                ('level', models.CharField(help_text='L0, L1, L2, L3, L4, L5, L6, L7, L8', max_length=4)),
                ('table_key', models.CharField(help_text='item_master, bom_master, r3ss_plan, …', max_length=40)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=False, help_text='Only the latest successful upload per table_key is current.')),
                ('parse_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppc_data_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PPCDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(default=0)),
                ('table_key', models.CharField(db_index=True, max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ppc_data.ppcuploadbatch')),
            ],
            options={
                'ordering': ['sr_no'],
            },
        ),
        migrations.CreateModel(
            name='PPCComputeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compute_key', models.CharField(max_length=40)),
                ('tiles', models.JSONField(default=dict)),
                ('tile_rows', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ppc_data.ppcuploadbatch')),
            ],
            options={
                'ordering': ['compute_key'],
            },
        ),
        migrations.AddIndex(
            model_name='ppcuploadbatch',
            index=models.Index(fields=['table_key', '-uploaded_at'], name='ppc_data_pp_table_k_efc9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='ppcdatarow',
            index=models.Index(fields=['table_key', 'batch'], name='ppc_data_pp_table_k_65bee7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ppccomputeresult',
            constraint=models.UniqueConstraint(fields=('batch', 'compute_key'), name='uniq_ppc_batch_compute'),
        ),
    ]
