# Generated by Django 6.0.8 on 2026-08-26 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPCDemandFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=40)),
                ('month', models.CharField(help_text='YYYY-MM format, e.g. 2026-09', max_length=7)),
                ('initial_qty', models.FloatField()),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, help_text='The upload batch that created this freeze', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_freezes', to='ppc_data.ppcuploadbatch')),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_freezes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='PPCDemandTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('add', 'Addition'), ('reduce', 'Reduction')], max_length=8)),
                ('qty', models.FloatField(help_text='Always positive; sign inferred from tx_type')),
                ('week', models.CharField(blank=True, help_text='Week label: W1, W2, Additional, etc.', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_transactions', to='ppc_data.ppcuploadbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_transactions', to=settings.AUTH_USER_MODEL)),
                ('freeze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ppc_data.ppcdemandfreeze')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ppcdemandfreeze',
            index=models.Index(fields=['month', 'item_code'], name='ppc_data_pp_month_8b43ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='ppcdemandfreeze',
            constraint=models.UniqueConstraint(fields=('item_code', 'month'), name='uniq_demand_freeze_item_month'),
        ),
        migrations.AddIndex(
            model_name='ppcdemandtransaction',
            index=models.Index(fields=['freeze', '-created_at'], name='ppc_data_pp_freeze__ed8b2d_idx'),
        ),
    ]
