# Generated by Django 6.0.8 on 2026-08-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc_data', '0002_demand_freeze'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPCFeasibilityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_month', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('flagged', 'Flagged — has unresolved issues'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict, help_text='Capacity flags, machine overloads, EBQ flags — counts and details')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_runs', to='ppc_data.ppcuploadbatch')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PPCRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_month', models.CharField(max_length=7)),
                ('release_number', models.PositiveIntegerField(help_text='Sequential within a month (1, 2, 3…)')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('recalled', 'Recalled')], default='active', max_length=20)),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('recall_reason', models.TextField(blank=True)),
                ('row_count', models.IntegerField(default=0)),
                ('summary', models.JSONField(default=dict, help_text='total_plan, sections, date_range')),
                ('feasibility_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ppc_data.ppcfeasibilityrun')),
                ('recalled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snapshot_batch', models.ForeignKey(blank=True, help_text='Batch holding the release_rows snapshot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_snapshots', to='ppc_data.ppcuploadbatch')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='ppc_data.ppcuploadbatch')),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='PPCProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_code', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('shift', models.CharField(blank=True, default='general', max_length=20)),
                ('produced_qty', models.FloatField()),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to='ppc_data.ppcrelease')),
            ],
            options={
                'ordering': ['-date', 'section', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='PPCCapacityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('capacity', 'Capacity overload'), ('machine', 'Machine overload'), ('ebq', 'Under-EBQ batch')], max_length=20)),
                ('date', models.DateField(blank=True, help_text='Day of overload (null for EBQ)', null=True)),
                ('product_group', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('item_code', models.CharField(blank=True, help_text='Specific item (EBQ flags)', max_length=100)),
                ('planned_qty', models.FloatField(default=0)),
                ('capacity_qty', models.FloatField(default=0, help_text='Available capacity / EBQ minimum')),
                ('overload_pct', models.FloatField(default=0, help_text='(planned - capacity) / capacity × 100')),
                ('detail', models.JSONField(default=dict, help_text='Machine code, utilization breakdown, etc.')),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('reason_text', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='ppc_data.ppcfeasibilityrun')),
            ],
            options={
                'ordering': ['flag_type', 'date', 'product_group'],
                'indexes': [models.Index(fields=['run', 'flag_type'], name='ppc_data_pp_run_id_b6aea7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PPCRejectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_code', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('stage', models.CharField(help_text='From operation_stage_map (W1.5)', max_length=100)),
                ('rejected_qty', models.FloatField()),
                ('reason_code', models.CharField(max_length=100)),
                ('reason_text', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'section'],
                'indexes': [models.Index(fields=['date', 'section'], name='ppc_data_pp_date_04869a_idx'), models.Index(fields=['item_code', 'date'], name='ppc_data_pp_item_co_4d1cd2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ppcrelease',
            constraint=models.UniqueConstraint(fields=('plan_month', 'release_number'), name='uniq_release_month_number'),
        ),
        migrations.AddIndex(
            model_name='ppcproductionentry',
            index=models.Index(fields=['date', 'section'], name='ppc_data_pp_date_08c744_idx'),
        ),
        migrations.AddIndex(
            model_name='ppcproductionentry',
            index=models.Index(fields=['item_code', 'date'], name='ppc_data_pp_item_co_32fa4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ppcproductionentry',
            constraint=models.UniqueConstraint(fields=('date', 'item_code', 'section', 'shift'), name='uniq_production_entry'),
        ),
    ]
