# Generated by Django 6.0.8 on 2026-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc_data', '0003_l5_l8_downstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcuploadbatch',
            name='file_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
