# Generated by Django 6.0.8 on 2026-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc_data', '0004_file_removed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppccapacityflag',
            name='flag_type',
            field=models.CharField(choices=[('capacity', 'Capacity overload'), ('machine', 'Machine overload'), ('ebq', 'Under-EBQ batch'), ('manpower', 'Manpower overload')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ppcfeasibilityrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('flagged', 'Flagged — has unresolved issues'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded by a later run')], default='pending', max_length=20),
        ),
    ]
