# Generated by Django 6.0.8 on 2026-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc_data', '0005_feasibility_manpower_superseded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcrelease',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Formal lot ID: JCPL-YYMM-NNN (e.g. JCPL-2609-001)', max_length=20),
        ),
    ]
