# Generated by Django 6.0.8 on 2026-08-19 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_dashboards', '0002_tile_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_key', models.CharField(max_length=20)),
                ('tiles', models.JSONField()),
                ('tile_rows', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_results', to='purchase_dashboards.purchasedashsnapshot')),
            ],
            options={
                'ordering': ['control_key'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'control_key'), name='uniq_snap_control')],
            },
        ),
        migrations.CreateModel(
            name='ControlRunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_key', models.CharField(max_length=20)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('verdict_counts', models.JSONField(default=dict)),
                ('population', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_history', to='purchase_dashboards.purchasedashsnapshot')),
            ],
            options={
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['control_key', '-run_at'], name='purchase_co_control_e385a9_idx')],
            },
        ),
    ]
