# Generated by Django 6.0.8 on 2026-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=120, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('first_qty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['first_seen'],
                'indexes': [models.Index(fields=['item_key'], name='purchase_co_item_ke_59cbc1_idx')],
            },
        ),
    ]
