# Generated by Django 6.0.8 on 2026-08-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_controls', '0002_requirementage'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_id', models.CharField(max_length=100)),
                ('gid', models.CharField(max_length=32)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=True)),
                ('fetch_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=64)),
                ('item_code', models.CharField(blank=True, max_length=120)),
                ('data', models.JSONField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase_controls.posnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'item_code'], name='purchase_co_snapsho_4f22ca_idx'), models.Index(fields=['snapshot', 'po_number'], name='purchase_co_snapsho_b47d4f_idx')],
            },
        ),
    ]
