# Generated by Django 6.0.7 on 2026-08-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('H/R', 'H/R'), ('Accounts', 'Accounts'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Design and Operation', 'Design and Operation'), ('Sales and Operation', 'Sales and Operation'), ('Management', 'Management')], help_text='Which single department this Admin account can access — it drives the sidebar and blocks direct links to other modules. Ignored for Super Admin, who always sees everything.', max_length=100),
        ),
    ]
