# Generated by Django 6.0.7 on 2026-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Accounts', 'Accounts'), ('Aftermarket Sales', 'Aftermarket Sales'), ('Central Engineering', 'Central Engineering'), ('Costing', 'Costing'), ('Design & Development', 'Design & Development'), ('Despatch', 'Despatch'), ('Digital Marketing', 'Digital Marketing'), ('HR', 'HR'), ('IT', 'IT'), ('International Trade', 'International Trade'), ('Maintenance', 'Maintenance'), ('OEM Sales', 'OEM Sales'), ('Operations', 'Operations'), ('PPC', 'PPC'), ('Production', 'Production'), ('Purchase', 'Purchase'), ('Quality', 'Quality'), ('Safety', 'Safety'), ('Store', 'Store'), ('Technical Sourcing', 'Technical Sourcing'), ('Tool Room', 'Tool Room'), ('Management', 'Management')], help_text='Which single department this Admin account can access — it drives the sidebar and blocks direct links to other modules. Ignored for Super Admin, who always sees everything.', max_length=100),
        ),
    ]
