# Generated by Django 6.0.8 on 2026-09-07 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Accounts', 'Accounts'), ('Aftermarket Sales', 'Aftermarket Sales'), ('Central Engineering', 'Central Engineering'), ('Costing', 'Costing'), ('Design & Development', 'Design & Development'), ('Despatch', 'Despatch'), ('Digital Marketing', 'Digital Marketing'), ('HR', 'HR'), ('IT', 'IT'), ('International Trade', 'International Trade'), ('Maintenance', 'Maintenance'), ('OEM Sales', 'OEM Sales'), ('Operations', 'Operations'), ('PPC', 'PPC'), ('Production', 'Production'), ('Purchase', 'Purchase'), ('Quality', 'Quality'), ('S&OP', 'S&OP'), ('Safety', 'Safety'), ('Store', 'Store'), ('Technical Sourcing', 'Technical Sourcing'), ('Tool Room', 'Tool Room'), ('Management', 'Management')], help_text='Which single department this Admin account can access — it drives the sidebar and blocks direct links to other modules. Ignored for Super Admin, who always sees everything.', max_length=100),
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(help_text="Slug from portal.data.DEPARTMENTS, e.g. 'purchase', 'ppc'.", max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module_slug'],
                'unique_together': {('user', 'module_slug')},
            },
        ),
    ]
