# Generated by Django 6.0.8 on 2026-08-10 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MtoMtsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.CharField(max_length=200)),
                ('item_code', models.CharField(max_length=100)),
                ('sales_status', models.CharField(blank=True, max_length=8)),
                ('sales_reason', models.CharField(blank=True, max_length=500)),
                ('ops_status', models.CharField(blank=True, max_length=8)),
                ('ops_reason', models.CharField(blank=True, max_length=500)),
                ('system_suggested', models.CharField(blank=True, max_length=8)),
                ('trend_tag', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['item_group', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='MtoMtsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('sales_status', 'Sales status'), ('sales_reason', 'Sales reason'), ('ops_status', 'Operations status'), ('ops_reason', 'Operations reason')], max_length=32)),
                ('old_value', models.CharField(blank=True, max_length=500)),
                ('new_value', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mto_mts_changes', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='mto_mts.mtomtsitem')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MtoMtsCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(max_length=32)),
                ('month_index', models.PositiveIntegerField()),
                ('value', models.CharField(blank=True, max_length=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='mto_mts.mtomtsitem')),
            ],
            options={
                'ordering': ['month_index'],
            },
        ),
        migrations.CreateModel(
            name='MtoMtsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mto_mts.mtomtschange')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mto_mts_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MtoMtsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('month_label', models.CharField(blank=True, max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=16)),
                ('validation_notes', models.TextField(blank=True, help_text='Any parsing warnings/exceptions — see Section 3/5 of the brief.')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mto_mts_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='mtomtsitem',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mto_mts.mtomtsupload'),
        ),
        migrations.AddIndex(
            model_name='mtomtschange',
            index=models.Index(fields=['item', 'changed_at'], name='mto_mts_mto_item_id_0eb6de_idx'),
        ),
        migrations.AddIndex(
            model_name='mtomtscell',
            index=models.Index(fields=['item', 'month_index'], name='mto_mts_mto_item_id_676e84_idx'),
        ),
        migrations.AddIndex(
            model_name='mtomtsnotification',
            index=models.Index(fields=['recipient', 'seen_at'], name='mto_mts_mto_recipie_4a6793_idx'),
        ),
        migrations.AddIndex(
            model_name='mtomtsitem',
            index=models.Index(fields=['upload', 'item_code'], name='mto_mts_mto_upload__66f638_idx'),
        ),
    ]
