# Generated by Django 6.0.8 on 2026-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplanningupload',
            name='file_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
