# Generated by Django 6.0.8 on 2026-09-04 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SopMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY-MM format, e.g. "2026-09"', max_length=7, unique=True)),
                ('append1_csv', models.TextField(help_text='Full Append1 CSV text (46-column reconciliation)')),
                ('dashboard_json', models.JSONField(help_text='Complete demand_supply_overview API response')),
                ('item_count', models.PositiveIntegerField(default=0, help_text='Number of items in this snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen', models.BooleanField(default=False, help_text='True once the month has ended — no more updates')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'S&OP Monthly Snapshot',
                'verbose_name_plural': 'S&OP Monthly Snapshots',
                'ordering': ['-year_month'],
            },
        ),
    ]
